plugins {
    id "base.publishing-conventions"
    id "via.viaversion-maven-publishing"
}

publishing {
    publications {
        mavenJava {
            pom {
                name = "ViaProxyPlus"
                description = "Standalone Via* Proxy Software That Allow Players To Join EVERY Minecraft Server Versions From Classic, Alpha, Beta To Release AND EVEN BEDROCK With Some New Features PrayoadMii's Was Added!"
                url = "https://github.com/prayoadmii/ViaProxyPlus"
                licenses {
                    license {
                        name = "GPL-3.0 License"
                        url = "https://github.com/prayoadmii/ViaProxyPlus/blob/main/LICENSE"
                    }
                }
                developers {
                    developer {
                        id = "RK_01"
                    }
                }
                scm {
                    connection = "scm:git:git://github.com/prayoadmii/ViaProxyPlus.git"
                    developerConnection = "scm:git:ssh://github.com/prayoadmii/ViaProxyPlus.git"
                    url = "https://github.com/prayoadmii/ViaProxyPlus.git"
                }
            }
        }
    }
}
